version: '3.8'

services:
  # Aplicaciones
  shortener:
    build: .
    container_name: shortener1
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - internal

  # Redis
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly no
      - --maxmemory
      - 1gb
      - --maxmemory-policy
      - allkeys-lru
      - --maxclients
      - "50000"
      - --slowlog-log-slower-than
      - "0"
    ports:
      - "6379:6379"
    networks:
      - internal

  # k6 runner
  k6:
    image: grafana/k6:0.50.0
    container_name: k6
    volumes:
      - ./loadtest:/scripts
      - ./results:/results
    networks:
      - internal
    depends_on:
      - shortener-no-redis

networks:
  internal:
    driver: bridge
