version: '3.8'

services:
  redis_test:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly no
    networks:
      - internal

networks:
  internal:
    driver: bridge
