version: '3.8'

services:
  # Aplicación principal
  shortener:
    build: .
    container_name: shortener1
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - internal

  # Redis
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly no
      - --maxmemory
      - 1gb
      - --maxmemory-policy
      - allkeys-lru
      - --maxclients
      - "50000"
      - --slowlog-log-slower-than
      - "0"
    ports:
      - "6379:6379"
    networks:
      - internal

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus scrape
    networks:
      - internal
    depends_on:
      - jaeger
      - loki

  # Jaeger para trazas
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI Jaeger
      - "14250:14250" # gRPC Collector
    networks:
      - internal

  # Loki para logs
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - internal

  # Prometheus para métricas
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - internal

  # Grafana para dashboards
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - internal
    depends_on:
      - prometheus
      - loki
      - jaeger
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  internal:
    driver: bridge
