global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'shortener'
    metrics_path: /metrics
    static_configs:
      - targets: ['shortener:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
